services:
  - type: web
    name: tdr-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn DASHBOARD_FINAL:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18